<?php

namespace REK\DocwizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocfieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocfieldRepository extends EntityRepository
{
}
